spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

spaceX:
  api-url: https://api.spacexdata.com

openAI:
  api-key: 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