spring:
  datasource:
#    url: jdbc:postgresql://db:5432/db
    url: jdbc:postgresql://localhost:5432/db
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

spaceX:
  api-url: https://api.spacexdata.com

openAI:
  api-key: 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

jwt:
  secret: 566D597133743677397A244226452948404D635166546A576E5A723475377821
  access-token-expiration-time: 86400000
  refresh-token-expiration-time: 2592000000