server:
  port: 5000
spring:
  profiles:
    active: prod
  datasource:
    #    url: jdbc:postgresql://db:5432/db
    url: jdbc:postgresql://aacdatabase.cpmr4ihortn6.us-east-1.rds.amazonaws.com:5432/db
    username: michaeljamieson
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    #    hibernate:
    #      ddl-auto: create-drop
    #    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

spaceX:
  api-url: https://api.spacexdata.com

openAI:
  #  api-key: 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 #mikes
  api-key: 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

jwt:
  secret: 566D597133743677397A244226452948404D635166546A576E5A723475377821
  access-token-expiration-time: 86400000
  refresh-token-expiration-time: 2592000000