name: CI - Build Backend

on:
  pull_request:
    branches:
      - better_deploy_CI_Github
    paths:
      - backend/**

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15.2
        env:
          POSTGRES_USER: flexspeak123
          POSTGRES_PASSWORD: password123
          POSTGRES_DB: customer
        ports:
          - 5332:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          ref: better_deploy_CI_Github
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and run Unit/Integration Tests with Maven
        run: mvn -ntp -B verify
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          FLATICON_API_KEY: ${{ secrets.FLATICON_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
